// day157~day207(2021年3月~2021年7月）Vant+Uniapp+小程序商城案例+Vite+TypeScript+React/day204(06.16)-ReactHooks+常用API之useState+useEffect/随堂练习/袁旭东/shopping-cart/src/components/CartList/index.jsx
function CartList(props) {
  // 4.2 在事件的处理函数中, 调用父组件传给CartList的方法，并把参数传给这个方法
  const handlerDelete = (id) => {
    // console.log(id);
    props.deleteItem(id);
  }

  // 5.3 声明onChange事件的事件处理方法
  const handlerChange = (id, e) => {
    // 5.4 给父组件传: 1.type 2.id 3.num
    props.changeItem({
      type: "change",
      id: id,
      num: e.target.value
    })
  }

  const handlerAdd = (id) => {
    props.changeItem({
      type: "add",
      id: id
    })
  }

  // 1.3.渲染name
  return (
    <div>
      {
        props.list.map(item => (
          <div className="item" key={item.id}>
            <img src={item.img} alt="" />
            <div className="name">{item.name}</div>
            <div className="change">
              {/* eslint-disable-next-line */}
              <a href="#">－</a>
              {/* 5.1.渲染list中的商品数量 */}
              {/* 5.2.在input中声明OnChange事件 */}
              <input type="text" className="num" value={item.num} onChange={(e) => handlerChange(item.id, e)} />
              {/* eslint-disable-next-line */}
              <a href="#" onClick={() => handlerAdd(item.id)}>＋</a>
            </div>
            {/* 4.1 在CartList组件中 给删除按钮绑定事件(事件传参) */}
            <div className="del" onClick={() => handlerDelete(item.id)}>×</div>

            {/* <div className="del" onClick={() => { this.props.deleteItem(item.id) }}>×</div> */}
          </div>
        ))
      }
    </div>
  )

}

export default CartList

// day157~day207(2021年3月~2021年7月）Vant+Uniapp+小程序商城案例+Vite+TypeScript+React/day184(04.26)-Vite开发Vue(OptionAPI)+TypeScript项目+使用VueX和VueRouter/随堂练习/vite_ts_composition_cart/src/components/CartList/index.vue
<template>
  <div class="list">
    <div class="item" v-for="item in list" :key="item.id">
      <img :src="item.img" />
      <div class="name" v-text="item.name"></div>
      <div class="change">
        <a href="" @click.prevent="item.num <= 0 ? null : item.num--">－</a>
        <input type="text" class="num" v-model="item.num" />
        <a href="" @click.prevent="productAdd($event, item.id)">＋</a>
      </div>
      <div class="del" @click="$emit('del', item.id)">×</div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    list: {
      type: Array,
      required: true,
    },
  },
  setup(props, { emit }) {
    // 添加商品数量
    const productAdd = (e: MouseEvent, id: number) => {
      console.log(e);
      emit("add", id);
    };

    return {
      productAdd,
    };
  },
});
</script>

<style>
</style>
