// day184(04.26)-Vite开发Vue(OptionAPI)+TypeScript项目+使用VueX和VueRouter/随堂练习/vite_ts_composition_cart/src/components/CartTotal/index.vue
<template>
  <div class="total">
    <span>总价：{{ price }}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, PropType } from "vue";

export default defineComponent({
  props: {
    list: {
      type: Array as PropType<{ price: number; num: number }[]>,
      required: true,
    },
  },
  setup(props) {
    let price = computed(() => {
      let sum = 0;
      props.list.forEach((val) => {
        sum += val.price * val.num;
      });
      return sum;
    });

    return {
      price,
    };
  },
});
</script>

<style>
</style>

// day204(06.16)-ReactHooks+常用API之useState+useEffect/随堂练习/袁旭东/shopping-cart/src/components/CartTotal/index.jsx
import React from "react"

function CartTotal(props) {

  // 2.3.定义一个方法 用来计算总价
  const comutedTotal = () => {
    let sum = 0;
    props.list.forEach(item => {
      sum += item.price * item.num;
    });
    return sum;
  }


  // 1.3.渲染name
  return (
    <div className="total">
      <span>总价：{comutedTotal()}</span>
      <button>结算</button>
    </div>
  )

}

export default CartTotal
