// day190(05.11)-购物车案例/cart/src/components/CartTotal/index.jsx
import React from "react";

// 商品总价组件
class CartTotal extends React.Component {
  // 获取商品总价
  getTotalPrice = () => {
    let sum = 0;
    this.props.goodsList.forEach(val => {
      sum += val.num * val.price;
    });
    return sum;
  }

  render() {
    return (
      <div className="total">
        <span>总价：{this.getTotalPrice()}</span>
        <button>结算</button>
      </div>
    )
  }
}

export default CartTotal;

// day157~day207(2021年3月~2021年7月）Vant+Uniapp+小程序商城案例+Vite+TypeScript+React/day184(04.26)-Vite开发Vue(OptionAPI)+TypeScript项目+使用VueX和VueRouter/随堂练习/vite_ts_cart/src/components/CartTotal/index.vue
<template>
  <div class="total">
    <span>总价：{{ price }}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { product } from "../../types/interfaces";

export default defineComponent({
  props: {
    list: {
      type: Array,
      required: true,
    },
  },
  computed: {
    price(): number {
      let sum = 0;
      this.list.forEach((val: product) => {
        sum += val.price * val.num;
      });
      return sum;
    },
  },
});
</script>

<style>
</style>
