// day190(05.11)-购物车案例/cart/src/components/CartTotal/index.jsx
import React from "react";

// 商品总价组件
class CartTotal extends React.Component {
  // 获取商品总价
  getTotalPrice = () => {
    let sum = 0;
    this.props.goodsList.forEach(val => {
      sum += val.num * val.price;
    });
    return sum;
  }

  render() {
    return (
      <div className="total">
        <span>总价：{this.getTotalPrice()}</span>
        <button>结算</button>
      </div>
    )
  }
}

export default CartTotal;

// day184(04.26)-Vite开发Vue(OptionAPI)+TypeScript项目+使用VueX和VueRouter/随堂练习/vite_ts_composition_cart/src/components/CartTotal/index.vue
<template>
  <div class="total">
    <span>总价：{{ price }}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, PropType } from "vue";

export default defineComponent({
  props: {
    list: {
      type: Array as PropType<{ price: number; num: number }[]>,
      required: true,
    },
  },
  setup(props) {
    let price = computed(() => {
      let sum = 0;
      props.list.forEach((val) => {
        sum += val.price * val.num;
      });
      return sum;
    });

    return {
      price,
    };
  },
});
</script>

<style>
</style>
